# Generated by Django 3.0.5 on 2024-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='pricing',
            field=models.IntegerField(),
        ),
    ]
